export const POST_LOGIN_SUCCESS = "POST_LOGIN_SUCCESS";
export const POST_LOGIN_FAILED = "POST_LOGIN_FAILED";
export const POST_LOGIN_LOADING = "POST_LOGIN_LOADING";
export const CLEAR_LOGIN = 'CLEAR_LOGIN'
export const CLEAR_PROFILE = 'CLEAR_PROFILE'

export const POST_LOGOUT_SUCCESS = 'POST_LOGOUT_SUCCESS'
export const POST_LOGOUT_FAILED = 'POST_LOGOUT_FAILED'
export const POST_LOGOUT_LOADING = 'POST_LOGOUT_LOADING'
export const CLEAR_LOGOUT = 'CLEAR_LOGOUT'

export const GET_USER_SUCCESS = 'GET_USER_SUCCESS'
export const GET_USER_FAILED = 'GET_USER_FAILED'
export const GET_USER_LOADING = 'GET_USER_LOADING'

export const PUT_PROFILE_SUCCESS = 'PUT_PROFILE_SUCCESS'
export const PUT_PROFILE_FAILED = 'PUT_PROFILE_FAILED'
export const PUT_PROFILE_LOADING = 'PUT_PROFILE_LOADING'

export const GET_ALL_USERS_SUCCESS = 'GET_ALL_USERS_SUCCESS'
export const GET_ALL_USERS_FAILED = 'GET_ALL_USERS_FAILED'
export const GET_ALL_USERS_LOADING = 'GET_ALL_USERS_LOADING'

export const GET_ALL_CATEGORIES_SUCCESS = 'GET_ALL_CATEGORIES_SUCCESS'
export const GET_ALL_CATEGORIES_FAILED = 'GET_ALL_CATEGORIES_FAILED'
export const GET_ALL_CATEGORIES_LOADING = 'GET_ALL_CATEGORIES_LOADING'

export const GET_CATEGORY_BY_ID_SUCCESS = 'GET_CATEGORY_BY_ID_SUCCESS'
export const GET_CATEGORY_BY_ID_FAILED = 'GET_CATEGORY_BY_ID_FAILED'
export const GET_CATEGORY_BY_ID_LOADING = 'GET_CATEGORY_BY_ID_LOADING'

export const SET_OPEN_MODAL = 'SET_OPEN_MODAL'
export const SET_CLOSE_MODAL = 'SET_CLOSE_MODAL'

export const SET_OPEN_MODAL_UPDATE = 'SET_OPEN_MODAL_UPDATE'
export const SET_CLOSE_MODAL_UPDATE = 'SET_CLOSE_MODAL_UPDATE'

export const POST_CATEGORY_SUCCESS = 'POST_CATEGORY_SUCCESS'
export const POST_CATEGORY_FAILED = 'POST_CATEGORY_FAILED'
export const POST_CATEGORY_LOADING = 'POST_CATEGORY_LOADING'

export const DELETE_CATEGORY_SUCCESS = 'DELETE_CATEGORY_SUCCESS'
export const DELETE_CATEGORY_FAILED = 'DELETE_CATEGORY_FAILED'
export const DELETE_CATEGORY_LOADING = 'DELETE_CATEGORY_LOADING'

export const UPDATE_CATEGORY_SUCCESS = 'UPDATE_CATEGORY_SUCCESS'
export const UPDATE_CATEGORY_FAILED = 'UPDATE_CATEGORY_FAILED'
export const UPDATE_CATEGORY_LOADING = 'UPDATE_CATEGORY_LOADING'

export const CLEAR_CATEGORY = 'CLEAR_CATEGORY'
export const CLEAR_QUESTION = 'CLEAR_QUESTION'
export const CLEAR_TICKET = 'CLEAR_TICKET'

export const SET_SELECTED_ID = 'SET_SELECTED_ID'

export const GET_ALL_QUESTIONS_SUCCESS = 'GET_ALL_QUESTIONS_SUCCESS'
export const GET_ALL_QUESTIONS_FAILED = 'GET_ALL_QUESTIONS_FAILED'
export const GET_ALL_QUESTIONS_LOADING = 'GET_ALL_QUESTIONS_LOADING'

export const POST_QUESTION_SUCCESS = 'POST_QUESTION_SUCCESS'
export const POST_QUESTION_FAILED = 'POST_QUESTION_FAILED'
export const POST_QUESTION_LOADING = 'POST_QUESTION_LOADING'

export const DELETE_QUESTION_SUCCESS = 'DELETE_QUESTION_SUCCESS'
export const DELETE_QUESTION_FAILED = 'DELETE_QUESTION_FAILED'
export const DELETE_QUESTION_LOADING = 'DELETE_QUESTION_LOADING'

export const UPDATE_QUESTION_SUCCESS = 'UPDATE_QUESTION_SUCCESS'
export const UPDATE_QUESTION_FAILED = 'UPDATE_QUESTION_FAILED'
export const UPDATE_QUESTION_LOADING = 'UPDATE_QUESTION_LOADING'

export const SET_SEARCH = 'SET_SEARCH'
export const CLEAR_SEARCH = 'CLEAR_SEARCH'



export const GET_TICKETS_SUCCESS = 'GET_TICKETS_SUCCESS'
export const GET_TICKETS_LOADING = 'GET_TICKETS_LOADING'
export const GET_TICKETS_ERROR = 'GET_TICKETS_ERROR'

export const GET_EXPORTS_SUCCESS = 'GET_EXPORTS_SUCCESS'
export const GET_EXPORTS_LOADING = 'GET_EXPORTS_LOADING'
export const GET_EXPORTS_ERROR = 'GET_EXPORTS_ERROR'

export const CLEAR_EXPORT = 'CLEAR_EXPORT'
export const CLEAR_FILTER = 'CLEAR_FILTER'
export const CLEAR_RESETPASS = 'CLEAR_RESETPASS'

export const GET_WIDGETS_SUCCESS = 'GET_WIDGETS_SUCCESS'
export const GET_WIDGETS_LOADING = 'GET_WIDGETS_LOADING'
export const GET_WIDGETS_ERROR = 'GET_WIDGETS_ERROR'

export const PUT_TICKETS_COMPLETE_SUCCESS = 'PUT_TICKETS_COMPLETE_SUCCESS'
export const PUT_TICKETS_COMPLETE_LOADING = 'PUT_TICKETS_COMPLETE_LOADING'
export const PUT_TICKETS_COMPLETE_ERROR = 'PUT_TICKETS_COMPLETE_ERROR'

export const PUT_TICKETS_ACTIVE_SUCCESS = 'PUT_TICKETS_ACTIVE_SUCCESS'
export const PUT_TICKETS_ACTIVE_LOADING = 'PUT_TICKETS_ACTIVE_LOADING'
export const PUT_TICKETS_ACTIVE_ERROR = 'PUT_TICKETS_ACTIVE_ERROR'

export const PUT_RESETPASS_SUCCESS = 'PUT_RESETPASS_SUCCESS'
export const PUT_RESETPASS_LOADING = 'PUT_RESETPASS_LOADING'
export const PUT_RESETPASS_ERROR = 'PUT_RESETPASS_ERROR'

export const SET_FILTER = 'SET_FILTER'
export const SET_FILTER_TIME = 'SET_FILTER_TIME'


export const GET_MESSAGES_SUCCESS = 'GET_MESSAGES_SUCCESS'
export const GET_MESSAGES_LOADING = 'GET_MESSAGES_LOADING'
export const GET_MESSAGES_ERROR = 'GET_MESSAGES_ERROR'
export const CLEAR_MESSAGES = 'CLEAR_MESSAGES'

export const POST_MESSAGES_SUCCESS = 'POST_MESSAGES_SUCCESS'
export const POST_MESSAGES_LOADING = 'POST_MESSAGES_LOADING'
export const POST_MESSAGES_ERROR = 'POST_MESSAGES_ERROR'


